# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-05 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_publicationclinicaltrial_relationship_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteInvestigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('favorites_base_data', 'My favorites (Base Data)'), ('favorites_full_profile', 'My favorites (Full Profile)'), ('authors', 'Authors'), ('market_access', 'Market Access'), ('company_cooperation', 'Company Cooperation'), ('other', 'Other')], max_length=25)),
                ('request_file', models.FileField(blank=True, null=True, upload_to='requests')),
                ('favorites', models.BooleanField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('sent', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('completed', 'Completed'), ('deleted', 'Deleted')], default='pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UnlockedInvestigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('investigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MedicalExpert')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorsRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.Request')),
                ('year_from', models.PositiveSmallIntegerField()),
                ('year_to', models.PositiveSmallIntegerField()),
                ('topic_interest', models.TextField()),
                ('other_comments', models.TextField(blank=True, null=True)),
            ],
            bases=('client.request',),
        ),
        migrations.CreateModel(
            name='CompanyCooperationRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.Request')),
                ('companies_interest', models.TextField()),
                ('drugs_medical_devices_interest', models.TextField()),
                ('other_comments', models.TextField(blank=True, null=True)),
            ],
            bases=('client.request',),
        ),
        migrations.CreateModel(
            name='FavoritesBaseDataRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.Request')),
            ],
            bases=('client.request',),
        ),
        migrations.CreateModel(
            name='FavoritesFullProfileRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.Request')),
            ],
            bases=('client.request',),
        ),
        migrations.CreateModel(
            name='MarketAccessRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.Request')),
                ('topic_interest', models.TextField()),
                ('other_comments', models.TextField(blank=True, null=True)),
            ],
            bases=('client.request',),
        ),
        migrations.CreateModel(
            name='OtherRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.Request')),
                ('description', models.TextField()),
            ],
            bases=('client.request',),
        ),
    ]
