# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-05 05:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('app', '0003_auto_20180105_0548'),
        ('app_helpers', '0002_auto_20180105_0548'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unlockedinvestigator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoriteinvestigator',
            name='investigator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MedicalExpert'),
        ),
        migrations.AddField(
            model_name='favoriteinvestigator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='unlockedinvestigator',
            unique_together=set([('user', 'investigator')]),
        ),
        migrations.AddField(
            model_name='marketaccessrequest',
            name='countries_interest',
            field=models.ManyToManyField(to='app_helpers.Country'),
        ),
        migrations.AlterUniqueTogether(
            name='favoriteinvestigator',
            unique_together=set([('user', 'investigator')]),
        ),
        migrations.AddField(
            model_name='authorsrequest',
            name='countries_interest',
            field=models.ManyToManyField(to='app_helpers.Country'),
        ),
        migrations.AddField(
            model_name='authorsrequest',
            name='types_publication_interest',
            field=models.ManyToManyField(to='app_helpers.PublicationSubtype'),
        ),
    ]
