# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-05 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('app_helpers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationclinicaltrial',
            name='relationship_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_helpers.PublicationClinicalTrialRelationshipType'),
        ),
    ]
