# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-05 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveIngredientCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'Active Ingredient categories',
            },
        ),
        migrations.CreateModel(
            name='AdditionalMonitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AdministrationRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Biosimilar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CareerStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ClinicalTrialActiveIngredientRelationshipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ClinicalTrialAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ClinicalTrialAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ClinicalTrialBiospecimenRetention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ClinicalTrialCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ClinicalTrialEndpointClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ClinicalTrialEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ClinicalTrialGender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ClinicalTrialInstitutionRelationshipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ClinicalTrialInterventionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ClinicalTrialInterventionRelationshipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ClinicalTrialMasking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ClinicalTrialObservationalStudyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ClinicalTrialPrimaryPurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ClinicalTrialRecruitmentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'Clinical trial recruitment statuses',
            },
        ),
        migrations.CreateModel(
            name='ClinicalTrialStudyArmType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ClinicalTrialStudyPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ClinicalTrialStudyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ClinicalTrialTimePerspective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='CountryState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('symbol', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('code',),
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DosageForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DrugClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'Drug classes',
            },
        ),
        migrations.CreateModel(
            name='DrugStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'Drug statuses',
            },
        ),
        migrations.CreateModel(
            name='EventInstitutionRelationshipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='EventSubtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FocusAreaResearchInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Focus Area / Research Interest',
                'verbose_name_plural': 'Focus Areas / Research Interests',
            },
        ),
        migrations.CreateModel(
            name='InstitutionInstitutionRelationshipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='InstitutionSubtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='InterventionInstitutionRelationshipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='InterventionInterventionRelationshipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='InterventionSubtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'Localities',
            },
        ),
        migrations.CreateModel(
            name='MarketingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'Marketing statuses',
            },
        ),
        migrations.CreateModel(
            name='MedicalDeviceRegulatoryClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('id', 'name'),
                'verbose_name_plural': 'Medical device regulatory classes',
            },
        ),
        migrations.CreateModel(
            name='MedicalExpertClinicalTrialPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MedicalExpertEventPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MedicalExpertInstitutionFormOfPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MedicalExpertInstitutionNatureOfPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MedicalExpertInstitutionPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MedicalExpertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Specialty',
                'verbose_name_plural': 'Specialties',
            },
        ),
        migrations.CreateModel(
            name='MedicalExpertPublicationPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PersonGender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PublicationClinicalTrialRelationshipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PublicationSubtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RLD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'RLD',
                'verbose_name_plural': 'RLDs',
            },
        ),
        migrations.CreateModel(
            name='TherapeuticArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Object ID')),
                ('last_changed_on', models.DateTimeField(auto_now=True, null=True)),
                ('check_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
