from django.conf.urls import url
from . import views

urlpatterns = [
    # investigators
    url(
        r'^investigators/$',
        views.InvestigatorsListView.as_view(),
        name='get_investigators'
    ),
    url(
        r'^investigators-per-country/$',
        views.InvestigatorsPerCountryListView.as_view(),
        name='get_investigators_per_country'
    ),
    url(
        r'^investigators-per-profession/$',
        views.InvestigatorsPerProfessionListView.as_view(),
        name='get_investigators_per_profession'
    ),
    url(
        r'^investigators-per-specialty/$',
        views.InvestigatorsPerSpecialtyListView.as_view(),
        name='get_investigators_per_specialty'
    ),
    url(
        r'^investigator/(?P<pk>[0-9]+)/connections/$',
        views.InvestigatorConnectionsListView.as_view(),
        name='get_investigator_connections'
    ),
    url(
        r'^investigator/(?P<pk>[0-9]+)/connections-authors/$',
        views.InvestigatorConnectionsAuthorsListView.as_view(),
        name='get_investigator_connections_authors'
    ),
    url(
        r'^investigator/(?P<pk>[0-9]+)/'
        'connections-clinical-trial-collaborators/$',
        views.InvestigatorConnectionsCTCollaboratorListView.as_view(),
        name='get_investigator_connections_clinical_trial_collaborators'
    ),
    url(
        r'^investigator/(?P<pk>[0-9]+)/'
        'connections-event-participants/$',
        views.InvestigatorConnectionsEventParticipantListView.as_view(),
        name='get_investigator_connections_event_participants'
    ),
    url(
        r'^investigator/(?P<pk>[0-9]+)/'
        'connections-physicians/$',
        views.InvestigatorConnectionsPhysiciansListView.as_view(),
        name='get_investigator_connections_physicians'
    ),
    url(
        r'^investigator/(?P<pk>[0-9]+)/'
        'connections-researchers/$',
        views.InvestigatorConnectionsResearchersListView.as_view(),
        name='get_investigator_connections_researchers'
    ),
    url(
        r'^investigator/(?P<pk>[0-9]+)/affiliations-per-institution-type/$',
        views.InvestigatorAffiliationsPerInstitutionTypeListView.as_view(),
        name='get_investigator_affiliations_per_institution_type'
    ),
    url(
        r'^investigator/(?P<pk>[0-9]+)/affiliations-universities/$',
        views.InvestigatorAffiliationsUniversitiesListView.as_view(),
        name='get_investigator_affiliations_universities'
    ),
    url(
        r'^investigator/(?P<pk>[0-9]+)/affiliations-hospitals/$',
        views.InvestigatorAffiliationsHospitalsListView.as_view(),
        name='get_investigator_affiliations_hospitals'
    ),
    url(
        r'^investigator/(?P<pk>[0-9]+)/affiliations-associations/$',
        views.InvestigatorAffiliationsAssociationsListView.as_view(),
        name='get_investigator_affiliations_associations'
    ),
    url(
        r'^investigator/(?P<pk>[0-9]+)/cooperations-per-company/$',
        views.InvestigatorCompanyCooperationsPerCompanyListView.as_view(),
        name='get_investigator_cooperations_per_company'
    ),
    url(
        r'^investigator/(?P<pk>[0-9]+)/cooperations-per-nature-of-payment/$',
        views. \
        InvestigatorCompanyCooperationsPerNatureOfPaymentListView.as_view(),
        name='get_investigator_company_cooperations_per_nature_of_payment'
    ),
    url(
        r'^investigator/(?P<pk>[0-9]+)/company-cooperations/$',
        views.InvestigatorCompanyCooperationsListView.as_view(),
        name='get_investigator_company_cooperations'
    ),
    url(
        r'^investigator/(?P<pk>[0-9]+)/clinical-trials-per-condition/$',
        views.InvestigatorClinicalTrialsPerConditionListView.as_view(),
        name='get_investigator_clinical_trials_per_condition'
    ),
    url(
        r'^investigator/(?P<pk>[0-9]+)/clinical-trials-per-sponsor/$',
        views.InvestigatorClinicalTrialsPerSponsorListView.as_view(),
        name='get_investigator_clinical_trials_per_sponsor'
    ),
    url(
        r'^investigator/(?P<pk>[0-9]+)/clinical-trials-per-study-phase/$',
        views.InvestigatorClinicalTrialsPerStudyPhaseListView.as_view(),
        name='get_investigator_clinical_trials_per_study_phase'
    ),
    url(
        r'^investigator/(?P<pk>[0-9]+)/'
        'clinical-trials-per-intervention/$',
        views.InvestigatorClinicalTrialsPerInterventionListView.as_view(),
        name='get_investigator_clinical_trials_per_intervention'
    ),
    url(
        r'^investigator/(?P<pk>[0-9]+)/clinical-trials/$',
        views.InvestigatorClinicalTrialsListView.as_view(),
        name='get_investigator_clinical_trials'
    ),
    url(
        r'^investigator/(?P<pk>[0-9]+)/events-per-type/$',
        views.InvestigatorEventsPerTypeListView.as_view(),
        name='get_investigator_events_per_type'
    ),
    url(
        r'^investigator/(?P<pk>[0-9]+)/events-per-position/$',
        views.InvestigatorEventsPerPositionListView.as_view(),
        name='get_investigator_events_per_position'
    ),
    url(
        r'^investigator/(?P<pk>[0-9]+)/events/$',
        views.InvestigatorEventsListView.as_view(),
        name='get_investigator_events'
    ),
    url(
        r'^investigator/(?P<pk>[0-9]+)/publications-per-type/$',
        views.InvestigatorPublicationsPerTypeListView.as_view(),
        name='get_investigator_publications_per_type'
    ),
    url(
        r'^investigator/(?P<pk>[0-9]+)/publications-per-year/$',
        views.InvestigatorPublicationsPerYearListView.as_view(),
        name='get_investigator_publications_per_year'
    ),
    url(
        r'^investigator/(?P<pk>[0-9]+)/publications/$',
        views.InvestigatorPublicationsListView.as_view(),
        name='get_investigator_publications'
    ),
    # favorite investigators
    url(
        r'^favorite-investigators/$',
        views.FavoriteInvestigatorsListView.as_view(),
        name='get_favorite_investigators'
    ),
    # requests
    url(
        r'^requests/$',
        views.RequestsListView.as_view(),
        name='get_requests'
    ),
    # speakers
    url(
        r'^speakers/$',
        views.SpeakersListView.as_view(),
        name='get_speakers'
    ),
    url(
        r'^speakers-per-country/$',
        views.SpeakersPerCountryListView.as_view(),
        name='get_speakers_per_country'
    ),
    url(
        r'^speakers-per-profession/$',
        views.SpeakersPerProfessionListView.as_view(),
        name='get_speakers_per_profession'
    ),
    url(
        r'^speakers-per-specialty/$',
        views.SpeakersPerSpecialtyListView.as_view(),
        name='get_speakers_per_specialty'
    ),
]
